context:
  name: msmtp
  version: 1.8.28

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://marlam.de/msmtp/releases/${{ name }}-${{ version }}.tar.xz
  sha256: 3a57f155f54e4860f7dd42138d9bea1af615b99dfab5ab4cd728fc8c09a647a4

build:
  number: 0
  skip: win

outputs:
  - package:
      name: ${{ name }}
    build:
      script:
        - autoreconf -ivf
        - ./configure --prefix=$PREFIX --datarootdir=$PREFIX --with-tls=gnutls --with-libidn --with-libgsasl
        - make -j${CPU_COUNT}
        - make check
        - make install
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - automake
        - make
        - pkg-config
        - gettext
        - texinfo
        - xz-tools  # [osx]
      host:
        - gnutls
        - libgsasl >=2.1
      run:
        - ${{ pin_compatible('libgsasl', upper_bound='x') }}
    tests:
      - package_contents:
          bin:
            - msmtp
            - msmtpd
          files:
            - man/man1/msmtp.1
      - script:
        - msmtp --help
        - msmtpd --help

  - package:
      name: ${{ name }}-sendmail
    build:
      script:
        - ln -s msmtp $PREFIX/bin/sendmail
        - ln -s msmtp.1 $PREFIX/man/man1/sendmail.1
    requirements:
      host:
        - msmtp
      run:
        - msmtp
    tests:
      - package_contents:
          bin:
            - sendmail
          files:
            - man/man1/sendmail.1
    about:
      summary: Use msmtp as a sendmail alternative
      description: |
        Provides an alternative to the 'sendmail' tool. When sendmail is called
        it will call 'msmtp' instead.
      license: GPL-3.0-or-later

about:
  summary: msmtp is an SMTP client
  description: |
    In the default mode, it transmits a mail to an SMTP server which takes care
    of further delivery.

    To use this program with your mail user agent (MUA), create a configuration
    file with your mail account(s) and tell your MUA to call msmtp instead of
    /usr/sbin/sendmail.
  license: GPL-3.0-or-later
  license_file: COPYING
  homepage: https://marlam.de/msmtp/
  repository: https://git.marlam.de/gitweb/?p=msmtp.git

extra:
  feedstock-name: msmtp
  recipe-maintainers:
    - blmaier
